# Auto-generated by /home/j0sh1x/Lg_G7_ThinQ_Edk2/edk2_LG_G7_THINQ/../edk2/BaseTools/BuildEnv
if [ -z "$WORKSPACE" ]
then
  export WORKSPACE=/home/j0sh1x/Lg_G7_ThinQ_Edk2/edk2_LG_G7_THINQ/workspace
fi
if [ -z "$EDK_TOOLS_PATH" ]
then
  export EDK_TOOLS_PATH=/home/j0sh1x/Lg_G7_ThinQ_Edk2/edk2_LG_G7_THINQ/../edk2/BaseTools
fi
if [ -e /home/j0sh1x/Lg_G7_ThinQ_Edk2/edk2_LG_G7_THINQ/../edk2/BaseTools/Bin/Linux-x86_64 ]
then
  if [ ${PATH//home/j0sh1x/Lg_G7_ThinQ_Edk2/edk2_LG_G7_THINQ/../edk2/BaseTools/Bin/Linux-x86_64/} == $PATH ]
  then
    export PATH=/home/j0sh1x/Lg_G7_ThinQ_Edk2/edk2_LG_G7_THINQ/../edk2/BaseTools/Bin/Linux-x86_64:$PATH
  fi
fi
